{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ba2c7f9a-21de-43e9-b5d8-5e537b715db9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "# Import the data from both tabs in the \"Bank_Churn_Messy\" Excel file\n",
    "account_info = pd.read_excel('/Users/deepali/Desktop/Github Projects /Bank+Customer+Churn/Bank_Churn_Messy.xlsx')\n",
    "customer_info = pd.read_excel('/Users/deepali/Desktop/Github Projects /Bank+Customer+Churn/Bank_Churn_Messy.xlsx', sheet_name = 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "fb9f358f-efdb-4f4b-8ef9-2089065e4330",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Joining \"Account_Info\" to \"Customer_Info\" using the CustomerID column\n",
    "churn_data = account_info.merge(customer_info, how = 'left', on = 'CustomerId')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "0acc37c1-b222-43f1-9873-1e6aa5485b97",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CustomerId</th>\n",
       "      <th>Surname</th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure_x</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>Tenure_y</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>15634602</td>\n",
       "      <td>Hargrave</td>\n",
       "      <td>619</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>2</td>\n",
       "      <td>€101348.88</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>2</td>\n",
       "      <td>Yes</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>15634602</td>\n",
       "      <td>Hargrave</td>\n",
       "      <td>619</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>2</td>\n",
       "      <td>€101348.88</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>2</td>\n",
       "      <td>Yes</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>15647311</td>\n",
       "      <td>Hill</td>\n",
       "      <td>608</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>€112542.58</td>\n",
       "      <td>€83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>15619304</td>\n",
       "      <td>Onio</td>\n",
       "      <td>502</td>\n",
       "      <td>French</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>€113931.57</td>\n",
       "      <td>€159660.8</td>\n",
       "      <td>3</td>\n",
       "      <td>No</td>\n",
       "      <td>8</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>15701354</td>\n",
       "      <td>Boni</td>\n",
       "      <td>699</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1</td>\n",
       "      <td>€93826.63</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "      <td>No</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CustomerId   Surname  CreditScore Geography  Gender   Age  Tenure_x  \\\n",
       "0    15634602  Hargrave          619       FRA  Female  42.0         2   \n",
       "1    15634602  Hargrave          619       FRA  Female  42.0         2   \n",
       "2    15647311      Hill          608     Spain  Female  41.0         1   \n",
       "3    15619304      Onio          502    French  Female  42.0         8   \n",
       "4    15701354      Boni          699       FRA  Female  39.0         1   \n",
       "\n",
       "  EstimatedSalary    Balance  NumOfProducts HasCrCard  Tenure_y  \\\n",
       "0      €101348.88       €0.0              1       Yes         2   \n",
       "1      €101348.88       €0.0              1       Yes         2   \n",
       "2      €112542.58  €83807.86              1       Yes         1   \n",
       "3      €113931.57  €159660.8              3        No         8   \n",
       "4       €93826.63       €0.0              2        No         1   \n",
       "\n",
       "  IsActiveMember  Exited  \n",
       "0            Yes       1  \n",
       "1            Yes       1  \n",
       "2            Yes       0  \n",
       "3             No       1  \n",
       "4             No       0  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "adfc2abb-e52b-4ea3-b138-e83904414f94",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Since Tenure_x and Tenure_y have identical columns, we will drop it\n",
    "# Also, rename Tenure_x to tenure\n",
    "\n",
    "churn_data = churn_data.drop('Tenure_y', axis = 1).rename({'Tenure_x':'Tenure'},axis = 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "6429130c-7567-4346-8859-7aba80f8229a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CustomerId</th>\n",
       "      <th>Surname</th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>15634602</td>\n",
       "      <td>Hargrave</td>\n",
       "      <td>619</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>2</td>\n",
       "      <td>€101348.88</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>15634602</td>\n",
       "      <td>Hargrave</td>\n",
       "      <td>619</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>2</td>\n",
       "      <td>€101348.88</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>15647311</td>\n",
       "      <td>Hill</td>\n",
       "      <td>608</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>€112542.58</td>\n",
       "      <td>€83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>15619304</td>\n",
       "      <td>Onio</td>\n",
       "      <td>502</td>\n",
       "      <td>French</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>€113931.57</td>\n",
       "      <td>€159660.8</td>\n",
       "      <td>3</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>15701354</td>\n",
       "      <td>Boni</td>\n",
       "      <td>699</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1</td>\n",
       "      <td>€93826.63</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CustomerId   Surname  CreditScore Geography  Gender   Age  Tenure  \\\n",
       "0    15634602  Hargrave          619       FRA  Female  42.0       2   \n",
       "1    15634602  Hargrave          619       FRA  Female  42.0       2   \n",
       "2    15647311      Hill          608     Spain  Female  41.0       1   \n",
       "3    15619304      Onio          502    French  Female  42.0       8   \n",
       "4    15701354      Boni          699       FRA  Female  39.0       1   \n",
       "\n",
       "  EstimatedSalary    Balance  NumOfProducts HasCrCard IsActiveMember  Exited  \n",
       "0      €101348.88       €0.0              1       Yes            Yes       1  \n",
       "1      €101348.88       €0.0              1       Yes            Yes       1  \n",
       "2      €112542.58  €83807.86              1       Yes            Yes       0  \n",
       "3      €113931.57  €159660.8              3        No             No       1  \n",
       "4       €93826.63       €0.0              2        No             No       0  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "8a2b7092-f9b9-42fd-8140-d55d5efa3d40",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(10004, 13)"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "17e88650-55c4-4f18-8bd3-134d02b9523f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0         True\n",
       "1         True\n",
       "2        False\n",
       "3        False\n",
       "4        False\n",
       "         ...  \n",
       "9999     False\n",
       "10000     True\n",
       "10001     True\n",
       "10002     True\n",
       "10003     True\n",
       "Length: 10004, dtype: bool"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Check duplicate values\n",
    "churn_data.duplicated(keep = False)\n",
    "#keep = False will display all duplicate values;keep = 'first' wil display first duplicate occurence; keep = 'last' wil display first duplicate occurence"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "63fd2658-a3a5-4339-84f1-568c6900574b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CustomerId</th>\n",
       "      <th>Surname</th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>15634602</td>\n",
       "      <td>Hargrave</td>\n",
       "      <td>619</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>2</td>\n",
       "      <td>€101348.88</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>15634602</td>\n",
       "      <td>Hargrave</td>\n",
       "      <td>619</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>2</td>\n",
       "      <td>€101348.88</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>15647311</td>\n",
       "      <td>Hill</td>\n",
       "      <td>608</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>€112542.58</td>\n",
       "      <td>€83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>15619304</td>\n",
       "      <td>Onio</td>\n",
       "      <td>502</td>\n",
       "      <td>French</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>€113931.57</td>\n",
       "      <td>€159660.8</td>\n",
       "      <td>3</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>15701354</td>\n",
       "      <td>Boni</td>\n",
       "      <td>699</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1</td>\n",
       "      <td>€93826.63</td>\n",
       "      <td>€0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CustomerId   Surname  CreditScore Geography  Gender   Age  Tenure  \\\n",
       "0    15634602  Hargrave          619       FRA  Female  42.0       2   \n",
       "1    15634602  Hargrave          619       FRA  Female  42.0       2   \n",
       "2    15647311      Hill          608     Spain  Female  41.0       1   \n",
       "3    15619304      Onio          502    French  Female  42.0       8   \n",
       "4    15701354      Boni          699       FRA  Female  39.0       1   \n",
       "\n",
       "  EstimatedSalary    Balance  NumOfProducts HasCrCard IsActiveMember  Exited  \n",
       "0      €101348.88       €0.0              1       Yes            Yes       1  \n",
       "1      €101348.88       €0.0              1       Yes            Yes       1  \n",
       "2      €112542.58  €83807.86              1       Yes            Yes       0  \n",
       "3      €113931.57  €159660.8              3        No             No       1  \n",
       "4       €93826.63       €0.0              2        No             No       0  "
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "81ca3f7b-be5b-4603-ab0d-74d18c02db6d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Remove duplicate rows and columns \n",
    "churn_data = churn_data.drop_duplicates(keep = False)\n",
    "# keep = False will drop all duplicates - the 1st occurence and the last occurence"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "7c56f375-6eb4-42a8-a53c-0613dda246a3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(9998, 13)"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "e24f8dbb-b890-40b0-b0f5-fae4fb5f4cea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Index: 9998 entries, 2 to 9999\n",
      "Data columns (total 13 columns):\n",
      " #   Column           Non-Null Count  Dtype  \n",
      "---  ------           --------------  -----  \n",
      " 0   CustomerId       9998 non-null   int64  \n",
      " 1   Surname          9995 non-null   object \n",
      " 2   CreditScore      9998 non-null   int64  \n",
      " 3   Geography        9998 non-null   object \n",
      " 4   Gender           9998 non-null   object \n",
      " 5   Age              9995 non-null   float64\n",
      " 6   Tenure           9998 non-null   int64  \n",
      " 7   EstimatedSalary  9998 non-null   object \n",
      " 8   Balance          9998 non-null   object \n",
      " 9   NumOfProducts    9998 non-null   int64  \n",
      " 10  HasCrCard        9998 non-null   object \n",
      " 11  IsActiveMember   9998 non-null   object \n",
      " 12  Exited           9998 non-null   int64  \n",
      "dtypes: float64(1), int64(5), object(7)\n",
      "memory usage: 1.1+ MB\n"
     ]
    }
   ],
   "source": [
    "churn_data.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "38c0ef6b-c2e1-403e-8385-ad643bc59258",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CustomerId</th>\n",
       "      <th>Surname</th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>15647311</td>\n",
       "      <td>Hill</td>\n",
       "      <td>608</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>€112542.58</td>\n",
       "      <td>€83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>15619304</td>\n",
       "      <td>Onio</td>\n",
       "      <td>502</td>\n",
       "      <td>French</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>€113931.57</td>\n",
       "      <td>€159660.8</td>\n",
       "      <td>3</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CustomerId Surname  CreditScore Geography  Gender   Age  Tenure  \\\n",
       "2    15647311    Hill          608     Spain  Female  41.0       1   \n",
       "3    15619304    Onio          502    French  Female  42.0       8   \n",
       "\n",
       "  EstimatedSalary    Balance  NumOfProducts HasCrCard IsActiveMember  Exited  \n",
       "2      €112542.58  €83807.86              1       Yes            Yes       0  \n",
       "3      €113931.57  €159660.8              3        No             No       1  "
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.head(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "9055ab9f-75c1-47d0-8919-e8dea262e320",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Replace € with ''\n",
    "churn_data['EstimatedSalary'] = churn_data['EstimatedSalary'].str.replace('€', '')\n",
    "churn_data['Balance'] = churn_data['Balance'].str.replace('€', '')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "5bf1527c-4922-4c9c-9cb6-cb23db49de51",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CustomerId</th>\n",
       "      <th>Surname</th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>15647311</td>\n",
       "      <td>Hill</td>\n",
       "      <td>608</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>112542.58</td>\n",
       "      <td>83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>15619304</td>\n",
       "      <td>Onio</td>\n",
       "      <td>502</td>\n",
       "      <td>French</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>113931.57</td>\n",
       "      <td>159660.8</td>\n",
       "      <td>3</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CustomerId Surname  CreditScore Geography  Gender   Age  Tenure  \\\n",
       "2    15647311    Hill          608     Spain  Female  41.0       1   \n",
       "3    15619304    Onio          502    French  Female  42.0       8   \n",
       "\n",
       "  EstimatedSalary   Balance  NumOfProducts HasCrCard IsActiveMember  Exited  \n",
       "2       112542.58  83807.86              1       Yes            Yes       0  \n",
       "3       113931.57  159660.8              3        No             No       1  "
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.head(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "3e61fd49-f607-4dde-bb85-41715c43a549",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "CustomerId           int64\n",
       "Surname             object\n",
       "CreditScore          int64\n",
       "Geography           object\n",
       "Gender              object\n",
       "Age                float64\n",
       "Tenure               int64\n",
       "EstimatedSalary     object\n",
       "Balance             object\n",
       "NumOfProducts        int64\n",
       "HasCrCard           object\n",
       "IsActiveMember      object\n",
       "Exited               int64\n",
       "dtype: object"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Check the data types for each column and make any necessary fixes\n",
    "churn_data.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "addf0656-d29a-4c9a-8410-450ed1aa3aad",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Convert data \n",
    "churn_data['EstimatedSalary'] = churn_data['EstimatedSalary'].astype('float')\n",
    "churn_data['Balance'] = churn_data['Balance'].astype('float')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "0ae83a57-cfe5-4ec7-b06b-168ae141486e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "CustomerId           int64\n",
       "Surname             object\n",
       "CreditScore          int64\n",
       "Geography           object\n",
       "Gender              object\n",
       "Age                float64\n",
       "Tenure               int64\n",
       "EstimatedSalary    float64\n",
       "Balance            float64\n",
       "NumOfProducts        int64\n",
       "HasCrCard           object\n",
       "IsActiveMember      object\n",
       "Exited               int64\n",
       "dtype: object"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "eea093cf-298e-4376-a16e-45d1e6b15794",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "CustomerId         0\n",
       "Surname            3\n",
       "CreditScore        0\n",
       "Geography          0\n",
       "Gender             0\n",
       "Age                3\n",
       "Tenure             0\n",
       "EstimatedSalary    0\n",
       "Balance            0\n",
       "NumOfProducts      0\n",
       "HasCrCard          0\n",
       "IsActiveMember     0\n",
       "Exited             0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Check missing values \n",
    "churn_data.isna().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "425d854c-0a0b-4e1e-95be-623520705012",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CustomerId</th>\n",
       "      <th>Surname</th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>15728693</td>\n",
       "      <td>NaN</td>\n",
       "      <td>574</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Female</td>\n",
       "      <td>NaN</td>\n",
       "      <td>3</td>\n",
       "      <td>-999999.0</td>\n",
       "      <td>141349.43</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>122</th>\n",
       "      <td>15580203</td>\n",
       "      <td>NaN</td>\n",
       "      <td>674</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Male</td>\n",
       "      <td>NaN</td>\n",
       "      <td>6</td>\n",
       "      <td>-999999.0</td>\n",
       "      <td>120193.42</td>\n",
       "      <td>1</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9390</th>\n",
       "      <td>15756954</td>\n",
       "      <td>NaN</td>\n",
       "      <td>538</td>\n",
       "      <td>France</td>\n",
       "      <td>Female</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>-999999.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      CustomerId Surname  CreditScore Geography  Gender  Age  Tenure  \\\n",
       "29      15728693     NaN          574   Germany  Female  NaN       3   \n",
       "122     15580203     NaN          674     Spain    Male  NaN       6   \n",
       "9390    15756954     NaN          538    France  Female  NaN       2   \n",
       "\n",
       "      EstimatedSalary    Balance  NumOfProducts HasCrCard IsActiveMember  \\\n",
       "29          -999999.0  141349.43              1       Yes            Yes   \n",
       "122         -999999.0  120193.42              1        No             No   \n",
       "9390        -999999.0       0.00              1       Yes            Yes   \n",
       "\n",
       "      Exited  \n",
       "29         0  \n",
       "122        0  \n",
       "9390       0  "
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data[churn_data.isna().any(axis = 1) == True]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "966343d2-7fc9-48e7-b3bf-b0250b4cc58a",
   "metadata": {},
   "source": [
    "### Build a bar chart displaying the count of churners (Exited=1) vs. non-churners (Exited=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "4e924bbd-1b12-4a7c-a7f4-5667d15eef52",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CustomerId</th>\n",
       "      <th>Surname</th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>15647311</td>\n",
       "      <td>Hill</td>\n",
       "      <td>608</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>112542.58</td>\n",
       "      <td>83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>15619304</td>\n",
       "      <td>Onio</td>\n",
       "      <td>502</td>\n",
       "      <td>French</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>113931.57</td>\n",
       "      <td>159660.80</td>\n",
       "      <td>3</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>15701354</td>\n",
       "      <td>Boni</td>\n",
       "      <td>699</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1</td>\n",
       "      <td>93826.63</td>\n",
       "      <td>0.00</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>15737888</td>\n",
       "      <td>Mitchell</td>\n",
       "      <td>850</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>43.0</td>\n",
       "      <td>2</td>\n",
       "      <td>79084.10</td>\n",
       "      <td>125510.82</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>15574012</td>\n",
       "      <td>Chu</td>\n",
       "      <td>645</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Male</td>\n",
       "      <td>44.0</td>\n",
       "      <td>8</td>\n",
       "      <td>149756.71</td>\n",
       "      <td>113755.78</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CustomerId   Surname  CreditScore Geography  Gender   Age  Tenure  \\\n",
       "2    15647311      Hill          608     Spain  Female  41.0       1   \n",
       "3    15619304      Onio          502    French  Female  42.0       8   \n",
       "4    15701354      Boni          699       FRA  Female  39.0       1   \n",
       "5    15737888  Mitchell          850     Spain  Female  43.0       2   \n",
       "6    15574012       Chu          645     Spain    Male  44.0       8   \n",
       "\n",
       "   EstimatedSalary    Balance  NumOfProducts HasCrCard IsActiveMember  Exited  \n",
       "2        112542.58   83807.86              1       Yes            Yes       0  \n",
       "3        113931.57  159660.80              3        No             No       1  \n",
       "4         93826.63       0.00              2        No             No       0  \n",
       "5         79084.10  125510.82              1       Yes            Yes       0  \n",
       "6        149756.71  113755.78              2        No             No       1  "
      ]
     },
     "execution_count": 43,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "539e8963-d376-4738-963e-7d1e3163bf4a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Axes: xlabel='Exited'>"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAiMAAAGrCAYAAAASIZeZAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8hTgPZAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAh70lEQVR4nO3dfWyV9f3/8deh9Zx2aA+DyqHIoXTeYEeHg9OJLVa8PVqJCXMZ3Ujage2kASWlYkbXedf5Td2mWNxspXIXJppGYZmZ1XmWTSlWF+la5wQVBTy1ntq1bOcgM6205/cHP05ybIu9DoWPpzwfyZXsfM51nfM+ybo+d10Xp7ZwOBwWAACAIeNMDwAAAM5uxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgVKLpAUZiYGBAn3zyic477zzZbDbT4wAAgBEIh8M6cuSIpk6dqnHjhj//ERcx8sknn8jtdpseAwAAxKC9vV3Tpk0b9vm4iJHzzjtP0vEPk5KSYngaAAAwEqFQSG63O/J7fDhxESMnLs2kpKQQIwAAxJmvusWCG1gBAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRMcVIbW2tMjIylJSUJI/Ho6amppPuv337dl122WX6xje+obS0NC1btkw9PT0xDQwAAMYWyzHS0NCgsrIyVVZWqrW1VXl5ecrPz5ff7x9y/927d6uoqEjFxcV655139Oyzz+rNN99USUnJKQ8PAADin+UYWbdunYqLi1VSUqLMzEzV1NTI7Xarrq5uyP3feOMNzZgxQ6tWrVJGRoauvPJKLV++XHv27Dnl4QEAQPyzFCN9fX1qaWmR1+uNWvd6vWpubh7ymNzcXH388cdqbGxUOBzWp59+queee04LFy4c9n16e3sVCoWiNgAAMDZZipHu7m719/fL5XJFrbtcLnV2dg55TG5urrZv366CggLZ7XZNmTJFEyZM0G9/+9th36e6ulpOpzOyud1uK2MCAIA4EtMNrF/+U8DhcHjYPw+8d+9erVq1Svfee69aWlr00ksv6eDBgyotLR329SsqKhQMBiNbe3t7LGMCAIA4kGhl59TUVCUkJAw6C9LV1TXobMkJ1dXVmj9/vu6++25J0uzZszV+/Hjl5eXpwQcfVFpa2qBjHA6HHA6HldHGrBlrXzA9As6gQw8Nf/kSAMYqS2dG7Ha7PB6PfD5f1LrP51Nubu6Qx/zvf//TuHHRb5OQkCDp+BkVAABwdrN8maa8vFwbN27U5s2btW/fPq1evVp+vz9y2aWiokJFRUWR/W+55Rbt3LlTdXV1OnDggF577TWtWrVKl19+uaZOnTp6nwQAAMQlS5dpJKmgoEA9PT2qqqpSIBBQVlaWGhsblZ6eLkkKBAJR3zmydOlSHTlyRL/73e901113acKECbr22mv1q1/9avQ+BQAAiFu2cBxcKwmFQnI6nQoGg0pJSTE9zhnFPSNnF+4ZATCWjPT3N3+bBgAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo2KKkdraWmVkZCgpKUkej0dNTU3D7rt06VLZbLZB26xZs2IeGgAAjB2WY6ShoUFlZWWqrKxUa2ur8vLylJ+fL7/fP+T+69evVyAQiGzt7e2aOHGifvjDH57y8AAAIP5ZjpF169apuLhYJSUlyszMVE1Njdxut+rq6obc3+l0asqUKZFtz549+s9//qNly5YN+x69vb0KhUJRGwAAGJssxUhfX59aWlrk9Xqj1r1er5qbm0f0Gps2bdL111+v9PT0Yfeprq6W0+mMbG6328qYAAAgjliKke7ubvX398vlckWtu1wudXZ2fuXxgUBAL774okpKSk66X0VFhYLBYGRrb2+3MiYAAIgjibEcZLPZoh6Hw+FBa0PZunWrJkyYoEWLFp10P4fDIYfDEctoAAAgzlg6M5KamqqEhIRBZ0G6uroGnS35snA4rM2bN6uwsFB2u936pAAAYEyyFCN2u10ej0c+ny9q3efzKTc396THvvrqq/rggw9UXFxsfUoAADBmWb5MU15ersLCQmVnZysnJ0f19fXy+/0qLS2VdPx+j46ODm3bti3quE2bNmnevHnKysoanckBAMCYYDlGCgoK1NPTo6qqKgUCAWVlZamxsTHyr2MCgcCg7xwJBoPasWOH1q9fPzpTAwCAMcMWDofDpof4KqFQSE6nU8FgUCkpKabHOaNmrH3B9Ag4gw49tND0CAAwakb6+5u/TQMAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIyKKUZqa2uVkZGhpKQkeTweNTU1nXT/3t5eVVZWKj09XQ6HQxdeeKE2b94c08AAAGBsSbR6QENDg8rKylRbW6v58+drw4YNys/P1969ezV9+vQhj1m8eLE+/fRTbdq0SRdddJG6urp07NixUx4eAADEP1s4HA5bOWDevHmaO3eu6urqImuZmZlatGiRqqurB+3/0ksv6Uc/+pEOHDigiRMnxjRkKBSS0+lUMBhUSkpKTK8Rr2asfcH0CDiDDj200PQIADBqRvr729Jlmr6+PrW0tMjr9Uate71eNTc3D3nM888/r+zsbP3617/WBRdcoEsuuURr1qzR559/Puz79Pb2KhQKRW0AAGBssnSZpru7W/39/XK5XFHrLpdLnZ2dQx5z4MAB7d69W0lJSfrDH/6g7u5urVixQocPHx72vpHq6mo98MADVkYDAABxKqYbWG02W9TjcDg8aO2EgYEB2Ww2bd++XZdffrluvvlmrVu3Tlu3bh327EhFRYWCwWBka29vj2VMAAAQByydGUlNTVVCQsKgsyBdXV2DzpackJaWpgsuuEBOpzOylpmZqXA4rI8//lgXX3zxoGMcDoccDoeV0QAAQJyydGbEbrfL4/HI5/NFrft8PuXm5g55zPz58/XJJ5/os88+i6y9//77GjdunKZNmxbDyAAAYCyxfJmmvLxcGzdu1ObNm7Vv3z6tXr1afr9fpaWlko5fYikqKorsv2TJEk2aNEnLli3T3r17tWvXLt1999267bbblJycPHqfBAAAxCXL3zNSUFCgnp4eVVVVKRAIKCsrS42NjUpPT5ckBQIB+f3+yP7nnnuufD6f7rzzTmVnZ2vSpElavHixHnzwwdH7FAAAIG5Z/p4RE/ieEZwt+J4RAGPJafmeEQAAgNFGjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABhFjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABhFjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABhFjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABgVU4zU1tYqIyNDSUlJ8ng8ampqGnbfV155RTabbdD27rvvxjw0AAAYOyzHSENDg8rKylRZWanW1lbl5eUpPz9ffr//pMe99957CgQCke3iiy+OeWgAADB2WI6RdevWqbi4WCUlJcrMzFRNTY3cbrfq6upOetzkyZM1ZcqUyJaQkBDz0AAAYOywFCN9fX1qaWmR1+uNWvd6vWpubj7psXPmzFFaWpquu+46/e1vfzvpvr29vQqFQlEbAAAYmyzFSHd3t/r7++VyuaLWXS6XOjs7hzwmLS1N9fX12rFjh3bu3KmZM2fquuuu065du4Z9n+rqajmdzsjmdrutjAkAAOJIYiwH2Wy2qMfhcHjQ2gkzZ87UzJkzI49zcnLU3t6uhx9+WFddddWQx1RUVKi8vDzyOBQKESQAAIxRls6MpKamKiEhYdBZkK6urkFnS07miiuu0P79+4d93uFwKCUlJWoDAABjk6UYsdvt8ng88vl8Ues+n0+5ubkjfp3W1lalpaVZeWsAADBGWb5MU15ersLCQmVnZysnJ0f19fXy+/0qLS2VdPwSS0dHh7Zt2yZJqqmp0YwZMzRr1iz19fXpqaee0o4dO7Rjx47R/SQAACAuWY6RgoIC9fT0qKqqSoFAQFlZWWpsbFR6erokKRAIRH3nSF9fn9asWaOOjg4lJydr1qxZeuGFF3TzzTeP3qcAAABxyxYOh8Omh/gqoVBITqdTwWDwrLt/ZMbaF0yPgDPo0EMLTY8AAKNmpL+/+ds0AADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAqJhipLa2VhkZGUpKSpLH41FTU9OIjnvttdeUmJio7373u7G8LQAAGIMsx0hDQ4PKyspUWVmp1tZW5eXlKT8/X36//6THBYNBFRUV6brrrot5WAAAMPZYjpF169apuLhYJSUlyszMVE1Njdxut+rq6k563PLly7VkyRLl5OTEPCwAABh7LMVIX1+fWlpa5PV6o9a9Xq+am5uHPW7Lli368MMPdd99943ofXp7exUKhaI2AAAwNlmKke7ubvX398vlckWtu1wudXZ2DnnM/v37tXbtWm3fvl2JiYkjep/q6mo5nc7I5na7rYwJAADiSEw3sNpstqjH4XB40Jok9ff3a8mSJXrggQd0ySWXjPj1KyoqFAwGI1t7e3ssYwIAgDgwslMV/19qaqoSEhIGnQXp6uoadLZEko4cOaI9e/aotbVVd9xxhyRpYGBA4XBYiYmJevnll3XttdcOOs7hcMjhcFgZDQAAxClLZ0bsdrs8Ho98Pl/Uus/nU25u7qD9U1JS9Pbbb6utrS2ylZaWaubMmWpra9O8efNObXoAABD3LJ0ZkaTy8nIVFhYqOztbOTk5qq+vl9/vV2lpqaTjl1g6Ojq0bds2jRs3TllZWVHHT548WUlJSYPWAQDA2clyjBQUFKinp0dVVVUKBALKyspSY2Oj0tPTJUmBQOArv3MEAADgBFs4HA6bHuKrhEIhOZ1OBYNBpaSkmB7njJqx9gXTI+AMOvTQQtMjAMCoGenvb/42DQAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMIoYAQAARhEjAADAKGIEAAAYRYwAAACjiBEAAGAUMQIAAIwiRgAAgFHECAAAMCqmGKmtrVVGRoaSkpLk8XjU1NQ07L67d+/W/PnzNWnSJCUnJ+vSSy/Vo48+GvPAAABgbEm0ekBDQ4PKyspUW1ur+fPna8OGDcrPz9fevXs1ffr0QfuPHz9ed9xxh2bPnq3x48dr9+7dWr58ucaPH6/bb799VD4EAACIX7ZwOBy2csC8efM0d+5c1dXVRdYyMzO1aNEiVVdXj+g1br31Vo0fP16///3vR7R/KBSS0+lUMBhUSkqKlXHj3oy1L5geAWfQoYcWmh4BAEbNSH9/W7pM09fXp5aWFnm93qh1r9er5ubmEb1Ga2urmpubtWDBgmH36e3tVSgUitoAAMDYZClGuru71d/fL5fLFbXucrnU2dl50mOnTZsmh8Oh7OxsrVy5UiUlJcPuW11dLafTGdncbreVMQEAQByJ6QZWm80W9TgcDg9a+7Kmpibt2bNHTzzxhGpqavTMM88Mu29FRYWCwWBka29vj2VMAAAQByzdwJqamqqEhIRBZ0G6uroGnS35soyMDEnSd77zHX366ae6//779eMf/3jIfR0OhxwOh5XRAABAnLJ0ZsRut8vj8cjn80Wt+3w+5ebmjvh1wuGwent7rbw1AAAYoyz/097y8nIVFhYqOztbOTk5qq+vl9/vV2lpqaTjl1g6Ojq0bds2SdLjjz+u6dOn69JLL5V0/HtHHn74Yd15552j+DEAAEC8shwjBQUF6unpUVVVlQKBgLKystTY2Kj09HRJUiAQkN/vj+w/MDCgiooKHTx4UImJibrwwgv10EMPafny5aP3KQAAQNyy/D0jJvA9Izhb8D0jAMaS0/I9IwAAAKONGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEbFFCO1tbXKyMhQUlKSPB6Pmpqaht13586duuGGG3T++ecrJSVFOTk5+vOf/xzzwAAAYGyxHCMNDQ0qKytTZWWlWltblZeXp/z8fPn9/iH337Vrl2644QY1NjaqpaVF11xzjW655Ra1trae8vAAACD+2cLhcNjKAfPmzdPcuXNVV1cXWcvMzNSiRYtUXV09oteYNWuWCgoKdO+99w75fG9vr3p7eyOPQ6GQ3G63gsGgUlJSrIwb92asfcH0CDiDDj200PQIOIP4+T67nI0/36FQSE6n8yt/f1s6M9LX16eWlhZ5vd6oda/Xq+bm5hG9xsDAgI4cOaKJEycOu091dbWcTmdkc7vdVsYEAABxxFKMdHd3q7+/Xy6XK2rd5XKps7NzRK/xyCOP6OjRo1q8ePGw+1RUVCgYDEa29vZ2K2MCAIA4khjLQTabLepxOBwetDaUZ555Rvfff7/++Mc/avLkycPu53A45HA4YhkNAADEGUsxkpqaqoSEhEFnQbq6ugadLfmyhoYGFRcX69lnn9X1119vfVIAADAmWbpMY7fb5fF45PP5otZ9Pp9yc3OHPe6ZZ57R0qVL9fTTT2vhwrPvBh4AADA8y5dpysvLVVhYqOzsbOXk5Ki+vl5+v1+lpaWSjt/v0dHRoW3btkk6HiJFRUVav369rrjiishZleTkZDmdzlH8KAAAIB5ZjpGCggL19PSoqqpKgUBAWVlZamxsVHp6uiQpEAhEfefIhg0bdOzYMa1cuVIrV66MrP/kJz/R1q1bT/0TAACAuBbTDawrVqzQihUrhnzuy4HxyiuvxPIWAADgLMHfpgEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwChiBAAAGEWMAAAAo4gRAABgFDECAACMIkYAAIBRxAgAADCKGAEAAEbFFCO1tbXKyMhQUlKSPB6Pmpqaht03EAhoyZIlmjlzpsaNG6eysrJYZwUAAGOQ5RhpaGhQWVmZKisr1draqry8POXn58vv9w+5f29vr84//3xVVlbqsssuO+WBAQDA2GI5RtatW6fi4mKVlJQoMzNTNTU1crvdqqurG3L/GTNmaP369SoqKpLT6TzlgQEAwNhiKUb6+vrU0tIir9cbte71etXc3DxqQ/X29ioUCkVtAABgbLIUI93d3erv75fL5Ypad7lc6uzsHLWhqqur5XQ6I5vb7R611wYAAF8vMd3AarPZoh6Hw+FBa6eioqJCwWAwsrW3t4/aawMAgK+XRCs7p6amKiEhYdBZkK6urkFnS06Fw+GQw+EYtdcDAABfX5bOjNjtdnk8Hvl8vqh1n8+n3NzcUR0MAACcHSydGZGk8vJyFRYWKjs7Wzk5Oaqvr5ff71dpaamk45dYOjo6tG3btsgxbW1tkqTPPvtM//73v9XW1ia73a5vf/vbo/MpAABA3LIcIwUFBerp6VFVVZUCgYCysrLU2Nio9PR0Sce/5OzL3zkyZ86cyH9uaWnR008/rfT0dB06dOjUpgcAAHHPcoxI0ooVK7RixYohn9u6deugtXA4HMvbAACAswB/mwYAABhFjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABhFjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABhFjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABhFjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABgVU4zU1tYqIyNDSUlJ8ng8ampqOun+r776qjwej5KSkvStb31LTzzxREzDAgCAscdyjDQ0NKisrEyVlZVqbW1VXl6e8vPz5ff7h9z/4MGDuvnmm5WXl6fW1lb9/Oc/16pVq7Rjx45THh4AAMQ/yzGybt06FRcXq6SkRJmZmaqpqZHb7VZdXd2Q+z/xxBOaPn26ampqlJmZqZKSEt122216+OGHT3l4AAAQ/xKt7NzX16eWlhatXbs2at3r9aq5uXnIY15//XV5vd6otRtvvFGbNm3SF198oXPOOWfQMb29vert7Y08DgaDkqRQKGRl3DFhoPd/pkfAGXQ2/nf8bMbP99nlbPz5PvGZw+HwSfezFCPd3d3q7++Xy+WKWne5XOrs7BzymM7OziH3P3bsmLq7u5WWljbomOrqaj3wwAOD1t1ut5VxgbjjrDE9AYDT5Wz++T5y5IicTuewz1uKkRNsNlvU43A4PGjtq/Yfav2EiooKlZeXRx4PDAzo8OHDmjRp0knfB2NDKBSS2+1We3u7UlJSTI8DYBTx8312CYfDOnLkiKZOnXrS/SzFSGpqqhISEgadBenq6hp09uOEKVOmDLl/YmKiJk2aNOQxDodDDocjam3ChAlWRsUYkJKSwv9YAWMUP99nj5OdETnB0g2sdrtdHo9HPp8vat3n8yk3N3fIY3Jycgbt//LLLys7O3vI+0UAAMDZxfK/pikvL9fGjRu1efNm7du3T6tXr5bf71dpaamk45dYioqKIvuXlpbqo48+Unl5ufbt26fNmzdr06ZNWrNmzeh9CgAAELcs3zNSUFCgnp4eVVVVKRAIKCsrS42NjUpPT5ckBQKBqO8cycjIUGNjo1avXq3HH39cU6dO1WOPPaYf/OAHo/cpMKY4HA7dd999gy7VAYh//HxjKLbwV/17GwAAgNOIv00DAACMIkYAAIBRxAgAADCKGAEAAEYRIwAAwKiYvg4eGE0ff/yx6urq1NzcrM7OTtlsNrlcLuXm5qq0tJS/SQQAYxz/tBdG7d69W/n5+XK73fJ6vXK5XAqHw+rq6pLP51N7e7tefPFFzZ8/3/SoAEZZe3u77rvvPm3evNn0KDCMGIFR3/ve93TllVfq0UcfHfL51atXa/fu3XrzzTfP8GQATre33npLc+fOVX9/v+lRYBgxAqOSk5PV1tammTNnDvn8u+++qzlz5ujzzz8/w5MBOFXPP//8SZ8/cOCA7rrrLmIE3DMCs9LS0tTc3DxsjLz++utKS0s7w1MBGA2LFi2SzWbTyf4/r81mO4MT4euKGIFRa9asUWlpqVpaWnTDDTfI5XLJZrOps7NTPp9PGzduVE1NjekxAcQgLS1Njz/+uBYtWjTk821tbfJ4PGd2KHwtESMwasWKFZo0aZIeffRRbdiwIXK6NiEhQR6PR9u2bdPixYsNTwkgFh6PR//4xz+GjZGvOmuCswf3jOBr44svvlB3d7ckKTU1Veecc47hiQCciqamJh09elQ33XTTkM8fPXpUe/bs0YIFC87wZPi6IUYAAIBRfAMrAAAwihgBAABGESMAAMAoYgQAABhFjAA4o66++mqVlZWdlteeMWMG30sDxCFiBIAlS5culc1mG7QN9883v2znzp365S9/GXlMQADgS88AWHbTTTdpy5YtUWsOh2NEx06cOPF0jAQgjnFmBIBlDodDU6ZMidq++c1v6pVXXpHdbldTU1Nk30ceeUSpqakKBAKSoi/TXH311froo4+0evXqyBmWE5qbm3XVVVcpOTlZbrdbq1at0tGjRyPPd3V16ZZbblFycrIyMjK0ffv2M/PhAYw6YgTAqDkRGoWFhQoGg3rrrbdUWVmpJ598csg/eLhz505NmzZNVVVVCgQCkWB5++23deONN+rWW2/VP//5TzU0NGj37t264447IscuXbpUhw4d0l//+lc999xzqq2tVVdX1xn7rABGD5dpAFj2pz/9Seeee27U2s9+9jPdc889evDBB/WXv/xFt99+u9555x0VFhbq+9///pCvM3HiRCUkJOi8887TlClTIuu/+c1vtGTJksgZlIsvvliPPfaYFixYoLq6Ovn9fr344ot64403NG/ePEnSpk2blJmZeXo+MIDTihgBYNk111yjurq6qLUT94LY7XY99dRTmj17ttLT02O6ObWlpUUffPBB1KWXcDisgYEBHTx4UO+//74SExOVnZ0def7SSy/VhAkTYvo8AMwiRgBYNn78eF100UXDPt/c3CxJOnz4sA4fPqzx48dbev2BgQEtX75cq1atGvTc9OnT9d5770lS1D0mAOIX94wAGFUffvihVq9erSeffFJXXHGFioqKNDAwMOz+drtd/f39UWtz587VO++8o4suumjQZrfblZmZqWPHjmnPnj2RY9577z3997//PV0fC8BpRIwAsKy3t1ednZ1RW3d3t/r7+1VYWCiv16tly5Zpy5Yt+te//qVHHnlk2NeaMWOGdu3apY6ODnV3d0s6fv/J66+/rpUrV6qtrU379+/X888/rzvvvFOSNHPmTN1000366U9/qr///e9qaWlRSUmJkpOTz8jnBzC6iBEAlr300ktKS0uL2q688kr93//9nw4dOqT6+npJ0pQpU7Rx40b94he/UFtb25CvVVVVpUOHDunCCy/U+eefL0maPXu2Xn31Ve3fv195eXmaM2eO7rnnnqh/kbNlyxa53W4tWLBAt956q26//XZNnjz5tH92AKPPFg6Hw6aHAAAAZy/OjAAAAKOIEQAAYBQxAgAAjCJGAACAUcQIAAAwihgBAABGESMAAMAoYgQAABhFjAAAAKOIEQAAYBQxAgAAjPp/L2JVvk4qAIQAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "churn_data['Exited'].value_counts(normalize = True).plot.bar()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c0ce7067-5edb-47b9-ad90-1deb99f8becf",
   "metadata": {},
   "source": [
    "### Explore the categorical variables vs. the target, and look at the percentage of Churners by “Geography” and “Gender”"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9dae3dba-0082-475f-8b59-7abb9cf6e742",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "92c7e29a-0a7a-47fc-a83b-de25958d8b2c",
   "metadata": {},
   "source": [
    "Build box plots for each numeric field, broken out by churners vs. non-churners"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06acdcff-b787-413d-836b-64293d849fbc",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4d1daf31-5aa6-472f-9e57-84dc8527bc65",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "7d89368b-6045-446f-bbaa-dbca1ad3c16d",
   "metadata": {},
   "source": [
    "Build histograms for each numeric field, broken out by churners vs. non-churners"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4ec7a9a6-dd4f-4094-9431-a51f10ad3dd0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0b96976-da26-4a8a-9fbb-2b6103e65c58",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "684fcf7b-5201-4231-8e3b-7ee0876525fa",
   "metadata": {},
   "source": [
    "Create a new dataset that excludes any columns that aren’t be suitable for modeling"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "id": "b2feb5a4-38d4-423b-8925-92f6f5f91ee4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CustomerId</th>\n",
       "      <th>Surname</th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>15647311</td>\n",
       "      <td>Hill</td>\n",
       "      <td>608</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>112542.58</td>\n",
       "      <td>83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>15619304</td>\n",
       "      <td>Onio</td>\n",
       "      <td>502</td>\n",
       "      <td>French</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>113931.57</td>\n",
       "      <td>159660.80</td>\n",
       "      <td>3</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>15701354</td>\n",
       "      <td>Boni</td>\n",
       "      <td>699</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1</td>\n",
       "      <td>93826.63</td>\n",
       "      <td>0.00</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>15737888</td>\n",
       "      <td>Mitchell</td>\n",
       "      <td>850</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>43.0</td>\n",
       "      <td>2</td>\n",
       "      <td>79084.10</td>\n",
       "      <td>125510.82</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>15574012</td>\n",
       "      <td>Chu</td>\n",
       "      <td>645</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Male</td>\n",
       "      <td>44.0</td>\n",
       "      <td>8</td>\n",
       "      <td>149756.71</td>\n",
       "      <td>113755.78</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CustomerId   Surname  CreditScore Geography  Gender   Age  Tenure  \\\n",
       "2    15647311      Hill          608     Spain  Female  41.0       1   \n",
       "3    15619304      Onio          502    French  Female  42.0       8   \n",
       "4    15701354      Boni          699       FRA  Female  39.0       1   \n",
       "5    15737888  Mitchell          850     Spain  Female  43.0       2   \n",
       "6    15574012       Chu          645     Spain    Male  44.0       8   \n",
       "\n",
       "   EstimatedSalary    Balance  NumOfProducts HasCrCard IsActiveMember  Exited  \n",
       "2        112542.58   83807.86              1       Yes            Yes       0  \n",
       "3        113931.57  159660.80              3        No             No       1  \n",
       "4         93826.63       0.00              2        No             No       0  \n",
       "5         79084.10  125510.82              1       Yes            Yes       0  \n",
       "6        149756.71  113755.78              2        No             No       1  "
      ]
     },
     "execution_count": 69,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "churn_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "id": "3140e413-049b-4152-9905-e7b3d70003f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "modelling_df = churn_data.drop(['CustomerId','Surname'],axis = 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "66524260-334b-4730-9437-6040bbd9ea5b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Geography</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>HasCrCard</th>\n",
       "      <th>IsActiveMember</th>\n",
       "      <th>Exited</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>608</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>112542.58</td>\n",
       "      <td>83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>502</td>\n",
       "      <td>French</td>\n",
       "      <td>Female</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>113931.57</td>\n",
       "      <td>159660.80</td>\n",
       "      <td>3</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>699</td>\n",
       "      <td>FRA</td>\n",
       "      <td>Female</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1</td>\n",
       "      <td>93826.63</td>\n",
       "      <td>0.00</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>850</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Female</td>\n",
       "      <td>43.0</td>\n",
       "      <td>2</td>\n",
       "      <td>79084.10</td>\n",
       "      <td>125510.82</td>\n",
       "      <td>1</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>645</td>\n",
       "      <td>Spain</td>\n",
       "      <td>Male</td>\n",
       "      <td>44.0</td>\n",
       "      <td>8</td>\n",
       "      <td>149756.71</td>\n",
       "      <td>113755.78</td>\n",
       "      <td>2</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CreditScore Geography  Gender   Age  Tenure  EstimatedSalary    Balance  \\\n",
       "2          608     Spain  Female  41.0       1        112542.58   83807.86   \n",
       "3          502    French  Female  42.0       8        113931.57  159660.80   \n",
       "4          699       FRA  Female  39.0       1         93826.63       0.00   \n",
       "5          850     Spain  Female  43.0       2         79084.10  125510.82   \n",
       "6          645     Spain    Male  44.0       8        149756.71  113755.78   \n",
       "\n",
       "   NumOfProducts HasCrCard IsActiveMember  Exited  \n",
       "2              1       Yes            Yes       0  \n",
       "3              3        No             No       1  \n",
       "4              2        No             No       0  \n",
       "5              1       Yes            Yes       0  \n",
       "6              2        No             No       1  "
      ]
     },
     "execution_count": 75,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "modelling_df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2c2a85e5-422c-467d-8787-3860d04992dc",
   "metadata": {},
   "source": [
    "Create dummy variables for categorical fields"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 78,
   "id": "47468261-74bb-48f9-8b6d-cf4f418115f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "modelling_df = pd.get_dummies(data = modelling_df,drop_first = True )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "id": "5a1d4ca3-bdf1-493a-b8b0-4c3a6cf7aa74",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>Exited</th>\n",
       "      <th>Geography_France</th>\n",
       "      <th>Geography_French</th>\n",
       "      <th>Geography_Germany</th>\n",
       "      <th>Geography_Spain</th>\n",
       "      <th>Gender_Male</th>\n",
       "      <th>HasCrCard_Yes</th>\n",
       "      <th>IsActiveMember_Yes</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>608</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>112542.58</td>\n",
       "      <td>83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>502</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>113931.57</td>\n",
       "      <td>159660.80</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>699</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1</td>\n",
       "      <td>93826.63</td>\n",
       "      <td>0.00</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>850</td>\n",
       "      <td>43.0</td>\n",
       "      <td>2</td>\n",
       "      <td>79084.10</td>\n",
       "      <td>125510.82</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>645</td>\n",
       "      <td>44.0</td>\n",
       "      <td>8</td>\n",
       "      <td>149756.71</td>\n",
       "      <td>113755.78</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CreditScore   Age  Tenure  EstimatedSalary    Balance  NumOfProducts  \\\n",
       "2          608  41.0       1        112542.58   83807.86              1   \n",
       "3          502  42.0       8        113931.57  159660.80              3   \n",
       "4          699  39.0       1         93826.63       0.00              2   \n",
       "5          850  43.0       2         79084.10  125510.82              1   \n",
       "6          645  44.0       8        149756.71  113755.78              2   \n",
       "\n",
       "   Exited  Geography_France  Geography_French  Geography_Germany  \\\n",
       "2       0             False             False              False   \n",
       "3       1             False              True              False   \n",
       "4       0             False             False              False   \n",
       "5       0             False             False              False   \n",
       "6       1             False             False              False   \n",
       "\n",
       "   Geography_Spain  Gender_Male  HasCrCard_Yes  IsActiveMember_Yes  \n",
       "2             True        False           True                True  \n",
       "3            False        False          False               False  \n",
       "4            False        False          False               False  \n",
       "5             True        False           True                True  \n",
       "6             True         True          False               False  "
      ]
     },
     "execution_count": 82,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "modelling_df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "17114663-c4eb-4306-8524-aaaebd50eec4",
   "metadata": {},
   "source": [
    "## Create a new “balance_v_income” feature, which divides a customer’s bank balance by their estimated salary, then visualize that feature vs. churn status"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "d2541457-f9d3-4180-8b74-64af49e1a234",
   "metadata": {},
   "outputs": [],
   "source": [
    "modelling_df['balance_v_income'] = modelling_df['Balance'] / modelling_df['EstimatedSalary']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "c504d64e-310f-4e45-9290-6708a2b79c28",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CreditScore</th>\n",
       "      <th>Age</th>\n",
       "      <th>Tenure</th>\n",
       "      <th>EstimatedSalary</th>\n",
       "      <th>Balance</th>\n",
       "      <th>NumOfProducts</th>\n",
       "      <th>Exited</th>\n",
       "      <th>Geography_France</th>\n",
       "      <th>Geography_French</th>\n",
       "      <th>Geography_Germany</th>\n",
       "      <th>Geography_Spain</th>\n",
       "      <th>Gender_Male</th>\n",
       "      <th>HasCrCard_Yes</th>\n",
       "      <th>IsActiveMember_Yes</th>\n",
       "      <th>balance_v_income</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>608</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1</td>\n",
       "      <td>112542.58</td>\n",
       "      <td>83807.86</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>0.744677</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>502</td>\n",
       "      <td>42.0</td>\n",
       "      <td>8</td>\n",
       "      <td>113931.57</td>\n",
       "      <td>159660.80</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>1.401375</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   CreditScore   Age  Tenure  EstimatedSalary    Balance  NumOfProducts  \\\n",
       "2          608  41.0       1        112542.58   83807.86              1   \n",
       "3          502  42.0       8        113931.57  159660.80              3   \n",
       "\n",
       "   Exited  Geography_France  Geography_French  Geography_Germany  \\\n",
       "2       0             False             False              False   \n",
       "3       1             False              True              False   \n",
       "\n",
       "   Geography_Spain  Gender_Male  HasCrCard_Yes  IsActiveMember_Yes  \\\n",
       "2             True        False           True                True   \n",
       "3            False        False          False               False   \n",
       "\n",
       "   balance_v_income  \n",
       "2          0.744677  \n",
       "3          1.401375  "
      ]
     },
     "execution_count": 90,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "modelling_df.head(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "id": "8b6b49e0-e894-44ba-aa3e-43f96f03ec9f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Axes: ylabel='balance_v_income'>"
      ]
     },
     "execution_count": 98,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAk0AAAGKCAYAAAAR/3XJAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8hTgPZAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAtCklEQVR4nO3df1TVdZ7H8RcgXNGFOyLBlYYcKDINmTxYAjXqrD+yiTi7zVmbZKhpHZuJ1PDHNrpji3YKzGZp2rDUfoxNWridyaYmJVkzWROlQyGJ6YzG+hPEEi4kCgqf/aP1bldQv12v3As+H+fcc+Lzfd/vfX/75/vy8/1+P98AY4wRAAAALijQ1w0AAAD0BIQmAAAACwhNAAAAFhCaAAAALCA0AQAAWEBoAgAAsIDQBAAAYAGhCQAAwII+vm6gN+no6NCRI0cUFhamgIAAX7cDAAAsMMaoublZMTExCgw8/3wSocmLjhw5otjYWF+3AQAAPHDw4EF9//vfP+92QpMXhYWFSfrmf3p4eLiPuwEAAFY0NTUpNjbWdR4/H0KTF529JBceHk5oAgCgh7nYrTXcCA4AAGABoQkAAMACQhMAAIAFhCYAAAALCE0AAAAWEJoAAAAsIDQBAABYQGgCAACwgMUtAeAi2tvbVVVVpePHjysiIkJJSUkKCgrydVsAuhmhCQAuoLS0VM8//7zq6upcYw6HQ9nZ2Ro9erQPOwPQ3bg8BwDnUVpaqtzcXMXHx2vp0qVat26dli5dqvj4eOXm5qq0tNTXLQLoRgHGGOPrJnqLpqYm2e12OZ1O3j0H9HDt7e3KzMxUfHy8nnjiCQUG/v+/MTs6OrRgwQLV1NRo1apVXKoDejir529mmgCgC1VVVaqrq1NmZqZbYJKkwMBAZWZmqra2VlVVVT7qEEB3IzQBQBeOHz8uSYqLi+ty+9nxs3UAej9CEwB0ISIiQpJUU1PT5faz42frAPR+hCYA6EJSUpIcDodWr16tjo4Ot20dHR1avXq1Bg0apKSkJB91CKC7EZoAoAtBQUHKzs5WWVmZFixYoOrqarW0tKi6uloLFixQWVmZHnroIW4CB64gPD3nRTw9B/Q+Xa3TNGjQID300EOs0wT0ElbP34QmLyI0Ab0TK4IDvZvV8zcrggPARQQFBWnEiBG+bgOAj3FPEwAAgAWEJgAAAAsITQAAABYQmgAAACwgNAEAAFhAaAIAALCA0AQAAGABoQkAAMACQhMAAIAFPg1NpaWluuuuuxQTE6OAgAC9/fbbbtuNMVq4cKFiYmIUGhqqsWPHqrq62q2mtbVVM2bMUGRkpPr376+MjAwdOnTIraahoUFZWVmy2+2y2+3KyspSY2OjW82BAwd01113qX///oqMjNTMmTPV1tZ2OQ4bAAD0QD4NTSdOnNAPf/hDFRYWdrl9yZIlKigoUGFhoT7++GM5HA5NmDBBzc3NrpqcnBytXbtWRUVF2rJli77++mulp6ervb3dVTNlyhRVVlaquLhYxcXFqqysVFZWlmt7e3u77rzzTp04cUJbtmxRUVGR/vSnP2nOnDmX7+ABAEDPYvyEJLN27VrX3x0dHcbhcJjFixe7xk6dOmXsdrtZtmyZMcaYxsZGExwcbIqKilw1hw8fNoGBgaa4uNgYY8yuXbuMJLNt2zZXTVlZmZFkdu/ebYwxZt26dSYwMNAcPnzYVfPGG28Ym81mnE6n5WNwOp1G0nf6DgAA8C2r52+/vaeppqZGdXV1mjhxomvMZrNpzJgx2rp1qySpoqJCp0+fdquJiYlRYmKiq6asrEx2u12jRo1y1aSkpMhut7vVJCYmKiYmxlVz++23q7W1VRUVFeftsbW1VU1NTW4fAADQO/ltaKqrq5MkRUdHu41HR0e7ttXV1SkkJEQDBgy4YE1UVFSn/UdFRbnVnPs7AwYMUEhIiKumK/n5+a77pOx2u2JjY7/jUQIAgJ7Cb0PTWQEBAW5/G2M6jZ3r3Jqu6j2pOdf8+fPldDpdn4MHD16wLwAA0HP5bWhyOByS1Gmmp76+3jUr5HA41NbWpoaGhgvWHD16tNP+jx075lZz7u80NDTo9OnTnWagvs1msyk8PNztAwAAeie/DU1xcXFyOBwqKSlxjbW1tWnz5s1KS0uTJCUnJys4ONitpra2Vjt37nTVpKamyul0qry83FWzfft2OZ1Ot5qdO3eqtrbWVbNhwwbZbDYlJydf1uMEAAA9Qx9f/vjXX3+tvXv3uv6uqalRZWWlIiIidM011ygnJ0d5eXlKSEhQQkKC8vLy1K9fP02ZMkWSZLfbNXXqVM2ZM0cDBw5URESE5s6dq+HDh2v8+PGSpKFDh2rSpEmaNm2ali9fLkl68MEHlZ6eriFDhkiSJk6cqGHDhikrK0tPP/20jh8/rrlz52ratGnMHgEAgG90w5N857Vp0yYjqdPn/vvvN8Z8s+xAbm6ucTgcxmazmdGjR5vPPvvMbR8nT54006dPNxERESY0NNSkp6ebAwcOuNV89dVXJjMz04SFhZmwsDCTmZlpGhoa3Gr2799v7rzzThMaGmoiIiLM9OnTzalTp77T8bDkAAAAPY/V83eAMcb4MLP1Kk1NTbLb7XI6ncxQAQDQQ1g9f/vtPU0AAAD+hNAEAABgAaEJAADAAkITAACABYQmAAAACwhNAAAAFhCaAAAALCA0AQAAWEBoAgAAsIDQBAAAYAGhCQAAwAJCEwAAgAWEJgAAAAsITQAAABYQmgAAACwgNAEAAFhAaAIAALCA0AQAAGABoQkAAMACQhMAAIAFhCYAAAALCE0AAAAWEJoAAAAsIDQBAABYQGgCAACwgNAEAABgAaEJAADAAkITAACABYQmAAAACwhNAAAAFhCaAAAALCA0AQAAWEBoAgAAsIDQBAAAYAGhCQAAwAJCEwAAgAWEJgAAAAsITQAAABYQmgAAACwgNAEAAFhAaAIAALCA0AQAAGABoQkAAMACQhMAAIAFhCYAAAALCE0AAAAWEJoAAAAsIDQBAABYQGgCAACwgNAEAABgAaEJAADAAkITAACABX4fms6cOaMFCxYoLi5OoaGhio+P1+OPP66Ojg5XjTFGCxcuVExMjEJDQzV27FhVV1e77ae1tVUzZsxQZGSk+vfvr4yMDB06dMitpqGhQVlZWbLb7bLb7crKylJjY2N3HCYAAPBzfh+annrqKS1btkyFhYX6/PPPtWTJEj399NN67rnnXDVLlixRQUGBCgsL9fHHH8vhcGjChAlqbm521eTk5Gjt2rUqKirSli1b9PXXXys9PV3t7e2umilTpqiyslLFxcUqLi5WZWWlsrKyuvV4AQCAfwowxhhfN3Eh6enpio6O1ssvv+wa++lPf6p+/frptddekzFGMTExysnJ0W9+8xtJ38wqRUdH66mnntKvfvUrOZ1OXXXVVXrttdd0zz33SJKOHDmi2NhYrVu3Trfffrs+//xzDRs2TNu2bdOoUaMkSdu2bVNqaqp2796tIUOGXLTXpqYm2e12OZ1OhYeHX4b/GwAAwNusnr/9fqbptttu08aNG/XXv/5VkrRjxw5t2bJFP/nJTyRJNTU1qqur08SJE13fsdlsGjNmjLZu3SpJqqio0OnTp91qYmJilJiY6KopKyuT3W53BSZJSklJkd1ud9Wcq7W1VU1NTW4fAADQO/XxdQMX85vf/EZOp1M33HCDgoKC1N7erieffFL33nuvJKmurk6SFB0d7fa96Oho7d+/31UTEhKiAQMGdKo5+/26ujpFRUV1+v2oqChXzbny8/O1aNGiSztAAADQI/j9TNOaNWu0atUqvf766/rkk0/06quv6ne/+51effVVt7qAgAC3v40xncbOdW5NV/UX2s/8+fPldDpdn4MHD1o9LAAA0MP4/UzTv/zLv2jevHn62c9+JkkaPny49u/fr/z8fN1///1yOBySvpkpGjRokOt79fX1rtknh8OhtrY2NTQ0uM021dfXKy0tzVVz9OjRTr9/7NixTrNYZ9lsNtlsNu8cKAAA8Gt+P9PU0tKiwED3NoOCglxLDsTFxcnhcKikpMS1va2tTZs3b3YFouTkZAUHB7vV1NbWaufOna6a1NRUOZ1OlZeXu2q2b98up9PpqgEAAFcuv59puuuuu/Tkk0/qmmuu0Y033qhPP/1UBQUF+ud//mdJ31xSy8nJUV5enhISEpSQkKC8vDz169dPU6ZMkSTZ7XZNnTpVc+bM0cCBAxUREaG5c+dq+PDhGj9+vCRp6NChmjRpkqZNm6bly5dLkh588EGlp6dbenIOAAD0bn4fmp577jk99thjys7OVn19vWJiYvSrX/1K//Zv/+aqefTRR3Xy5EllZ2eroaFBo0aN0oYNGxQWFuaqeeaZZ9SnTx9NnjxZJ0+e1Lhx47Ry5UoFBQW5alavXq2ZM2e6nrLLyMhQYWFh9x0sAADwW36/TlNPwjpNAAD0PL1mnSYAAAB/QGgCAACwgNAEAABgAaEJAADAAkITAACABYQmAAAACwhNAAAAFhCaAAAALCA0AQAAWEBoAgAAsIDQBAAAYAGhCQAAwAJCEwAAgAWEJgAAAAsITQAAABYQmgAAACwgNAEAAFhAaAIAALDgkkJTW1ub9uzZozNnznirHwAAAL/kUWhqaWnR1KlT1a9fP9144406cOCAJGnmzJlavHixVxsEAADwBx6Fpvnz52vHjh368MMP1bdvX9f4+PHjtWbNGq81BwAA4C/6ePKlt99+W2vWrFFKSooCAgJc48OGDdO+ffu81hwAAIC/8Gim6dixY4qKiuo0fuLECbcQBQAA0Ft4FJpuvvlmvffee66/zwalF198Uampqd7pDAAAwI94dHkuPz9fkyZN0q5du3TmzBk9++yzqq6uVllZmTZv3uztHgEAAHzOo5mmtLQ0ffTRR2ppadG1116rDRs2KDo6WmVlZUpOTvZ2jwAAAD4XYIwxvm6it2hqapLdbpfT6VR4eLiv2wEAABZYPX97dHnurPr6etXX16ujo8NtPCkp6VJ2CwAA4Hc8Ck0VFRW6//779fnnn+vciaqAgAC1t7d7pTkAAAB/4VFoeuCBB3T99dfr5ZdfVnR0NMsMAACAXs+j0FRTU6O33npL1113nbf7AQAA8EsePT03btw47dixw9u9AAAA+C2PZppeeukl3X///dq5c6cSExMVHBzstj0jI8MrzQEAAPgLj0LT1q1btWXLFq1fv77TNm4EBwAAvZFHl+dmzpyprKws1dbWqqOjw+1DYAIAAL2RR6Hpq6++0qxZsxQdHe3tfgAAAPySR6Hp7rvv1qZNm7zdCwAAgN/y6J6m66+/XvPnz9eWLVs0fPjwTjeCz5w50yvNAQAA+AuP3j0XFxd3/h0GBOiLL764pKZ6Kt49BwBAz3NZ3z1XU1PjcWMAAAA9kUf3NH2bMabT++cAAAB6G49D0x//+EcNHz5coaGhCg0NVVJSkl577TVv9gYAAOA3PLo8V1BQoMcee0zTp0/XrbfeKmOMPvroI/3617/Wl19+qVmzZnm7TwAAAJ/y+EbwRYsW6b777nMbf/XVV7Vw4cIr9p4nbgQHAKDnsXr+9ujyXG1trdLS0jqNp6Wlqba21pNdAgAA+DWPQtN1112n//zP/+w0vmbNGiUkJFxyUwAAAP7Go3uaFi1apHvuuUelpaW69dZbFRAQoC1btmjjxo1dhikAAICezqOZpp/+9Kfavn27IiMj9fbbb+utt95SZGSkysvL9Y//+I/e7hEAAMDnPLoRHF3jRnAAAHqey3oj+Lp16/T+++93Gn///fe1fv16T3YJAADg1zwKTfPmzVN7e3uncWOM5s2bd8lNAQAA+BuPQtPf/vY3DRs2rNP4DTfcoL17915yUwAAAP7Go9Bkt9v1xRdfdBrfu3ev+vfvf8lNnevw4cP6+c9/roEDB6pfv3666aabVFFR4dpujNHChQsVExOj0NBQjR07VtXV1W77aG1t1YwZMxQZGan+/fsrIyNDhw4dcqtpaGhQVlaW7Ha77Ha7srKy1NjY6PXjAQAAPY9HoSkjI0M5OTnat2+fa2zv3r2aM2eOMjIyvNac9E2QufXWWxUcHKz169dr165d+vd//3d973vfc9UsWbJEBQUFKiws1McffyyHw6EJEyaoubnZVZOTk6O1a9eqqKhIW7Zs0ddff6309HS3y4xTpkxRZWWliouLVVxcrMrKSmVlZXn1eAAAQA9lPNDY2GhSUlJMnz59zA9+8APzgx/8wPTp08f8+Mc/Ng0NDZ7s8rx+85vfmNtuu+282zs6OozD4TCLFy92jZ06dcrY7XazbNkyV7/BwcGmqKjIVXP48GETGBhoiouLjTHG7Nq1y0gy27Ztc9WUlZUZSWb37t2WenU6nUaScTqd3+kYAQCA71g9f3t8eW7r1q167733lJ2drTlz5mjjxo364IMP3GaAvOGdd97RyJEj9U//9E+KiorSiBEj9OKLL7q219TUqK6uThMnTnSN2Ww2jRkzRlu3bpUkVVRU6PTp0241MTExSkxMdNWUlZXJbrdr1KhRrpqUlBTXsXaltbVVTU1Nbh8AANA7ebQiuCQFBARo4sSJbkHkcvjiiy/0wgsvaPbs2frXf/1XlZeXa+bMmbLZbLrvvvtUV1cnSYqOjnb7XnR0tPbv3y9JqqurU0hIiAYMGNCp5uz36+rqFBUV1en3o6KiXDXnys/P16JFiy75GAEAgP/zODRt3LhRGzduVH19vTo6Oty2vfLKK5fc2FkdHR0aOXKk8vLyJEkjRoxQdXW1XnjhBd13332uuoCAALfvGWM6jZ3r3Jqu6i+0n/nz52v27Nmuv5uamhQbG3vxgwIAAD2OR5fnFi1apIkTJ2rjxo368ssv1dDQ4PbxpkGDBnVa3mDo0KE6cOCAJMnhcEhSp9mg+vp61+yTw+FQW1tbp97OrTl69Gin3z927FinWayzbDabwsPD3T4AAKB38mimadmyZVq5cmW3PFl26623as+ePW5jf/3rXzV48GBJUlxcnBwOh0pKSjRixAhJUltbmzZv3qynnnpKkpScnKzg4GCVlJRo8uTJkqTa2lrt3LlTS5YskSSlpqbK6XSqvLxct9xyiyRp+/btcjqdSktLu+zHCQAA/JtHoamtra3bgsSsWbOUlpamvLw8TZ48WeXl5VqxYoVWrFgh6ZtLajk5OcrLy1NCQoISEhKUl5enfv36acqUKZK+uXF96tSpmjNnjgYOHKiIiAjNnTtXw4cP1/jx4yV9M3s1adIkTZs2TcuXL5ckPfjgg0pPT9eQIUO65VgBAIAf8+TRvEcffdQ8/vjjnnzVI++++65JTEw0NpvN3HDDDWbFihVu2zs6Okxubq5xOBzGZrOZ0aNHm88++8yt5uTJk2b69OkmIiLChIaGmvT0dHPgwAG3mq+++spkZmaasLAwExYWZjIzM7/TEgosOQAAQM9j9fwdYIwx3zVoPfLII/rjH/+opKQkJSUlKTg42G17QUGBlyJdz2L1LckAAMB/WD1/e3R5rqqqSjfddJMkaefOnW7bLvbEGgAAQE/kUWjatGmTt/sAAADwax4tOQAAAHClsTzTdPfdd2vlypUKDw/X3XfffcHat95665IbAwAA8CeWQ5Pdbnfdr2S32y9bQwAAAP7Io6fnrProo480cuRI2Wy2y/UTfoWn5wAA6Hmsnr8v6z1Nd9xxhw4fPnw5fwIAAKBbXNbQdBknsQAAALoVT88BAABYQGgCAACwgNAEAABgwWUNTbxSBQAA9BbcCA4AAGCBR6Fp0aJF2rdv30XrmpubFR8f78lPAAAA+BWPQtOf/vQnXX/99UpJSVFhYaGOHTvm7b4AAAD8ikehqaqqSlVVVfr7v/97FRQU6Oqrr9ZPfvITvf7662ppafF2jwAAAD7nldeofPTRR3r99df15ptv6tSpU2pqavJGbz0Or1EBAKDn6dbXqPTv31+hoaEKCQnR6dOnvbFLAAAAv+JxaKqpqdGTTz6pYcOGaeTIkfrkk0+0cOFC1dXVebM/AAAAv9DHky+lpqaqvLxcw4cP1wMPPKApU6bo6quv9nZvAAAAfsOj0PTjH/9YL730km688UZv9wMAAOCXPLo8l5eXZykwhYeH64svvvDkJwAAAPwKK4IDAABYwAt7AQAALCA0AQAAWEBoAgAAsOCyhqaAgIDLuXsAAIBuw43gAAAAFlxSaGpra9OePXt05syZLrevX7+eRS8BAECv4FFoamlp0dSpU9WvXz/deOONOnDggCRp5syZWrx4savutttuk81m806nAAAAPuRRaJo/f7527NihDz/8UH379nWNjx8/XmvWrPFacwAAAP7Co9eovP3221qzZo1SUlLcbvYeNmyY9u3b57XmAAAA/IVHM03Hjh1TVFRUp/ETJ07wxBwAAOiVPApNN998s9577z3X32eD0osvvqjU1FTvdAYAAOBHPLo8l5+fr0mTJmnXrl06c+aMnn32WVVXV6usrEybN2/2do8AAAA+59FMU1pamj766CO1tLTo2muv1YYNGxQdHa2ysjIlJyd7u0cAAACfCzCsQOk1TU1NstvtcjqdCg8P93U7AADAAqvnb49mmtatW6f333+/0/j777+v9evXe7JLAAAAv+ZRaJo3b57a29s7jRtjNG/evEtuCgAAwN94FJr+9re/adiwYZ3Gb7jhBu3du/eSmwIAAPA3HoUmu92uL774otP43r171b9//0tuCgAAwN94FJoyMjKUk5Pjtvr33r17NWfOHGVkZHitOQAAAH/hUWh6+umn1b9/f91www2Ki4tTXFychg4dqoEDB+p3v/udt3sEAADwOY8Wt7Tb7dq6datKSkq0Y8cOhYaGKikpSaNHj/Z2fwAAAH6BdZq8iHWaAADoeayevz2aaZKkjRs3auPGjaqvr1dHR4fbtldeecXT3QIAAPglj0LTokWL9Pjjj2vkyJEaNGiQ64W9AAAAvZVHoWnZsmVauXKlsrKyvN0PAACAX/Lo6bm2tjalpaV5uxcAAAC/5VFo+uUvf6nXX3/d270AAAD4LY8uz506dUorVqzQf/3XfykpKUnBwcFu2wsKCrzSHAAAgL/wKDRVVVXppptukiTt3LnTbRs3hQMAgN7Io9C0adMmb/cBAADg1zy6p8lX8vPzFRAQoJycHNeYMUYLFy5UTEyMQkNDNXbsWFVXV7t9r7W1VTNmzFBkZKT69++vjIwMHTp0yK2moaFBWVlZstvtstvtysrKUmNjYzccFQAA6Ak8Xtzy448/1ptvvqkDBw6ora3Nbdtbb711yY119XsrVqxQUlKS2/iSJUtUUFCglStX6vrrr9cTTzyhCRMmaM+ePQoLC5Mk5eTk6N1331VRUZEGDhyoOXPmKD09XRUVFQoKCpIkTZkyRYcOHVJxcbEk6cEHH1RWVpbeffddrx8LAADogYwH3njjDRMcHGzuvPNOExISYtLT082QIUOM3W43v/jFLzzZ5QU1NzebhIQEU1JSYsaMGWMeeeQRY4wxHR0dxuFwmMWLF7tqT506Zex2u1m2bJkxxpjGxkYTHBxsioqKXDWHDx82gYGBpri42BhjzK5du4wks23bNldNWVmZkWR2795tuU+n02kkGafTeSmHCwAAupHV87dHl+fy8vL0zDPP6C9/+YtCQkL07LPP6vPPP9fkyZN1zTXXeDPTSZIefvhh3XnnnRo/frzbeE1Njerq6jRx4kTXmM1m05gxY7R161ZJUkVFhU6fPu1WExMTo8TERFdNWVmZ7Ha7Ro0a5apJSUlxvZj4fFpbW9XU1OT2AQAAvZNHoWnfvn268847JX0TUk6cOKGAgADNmjVLK1as8GqDRUVF+uSTT5Sfn99pW11dnSQpOjrabTw6Otq1ra6uTiEhIRowYMAFa6KiojrtPyoqylXTlfz8fNc9UHa7XbGxsd/t4AAAQI/hUWiKiIhQc3OzJOnqq692LTvQ2NiolpYWrzV38OBBPfLII1q1apX69u173rpzlzkwxlx06YNza7qqv9h+5s+fL6fT6focPHjwgr8JAAB6Lo9C049+9COVlJRIkiZPnqxHHnlE06ZN07333qtx48Z5rbmKigrV19crOTlZffr0UZ8+fbR582b9x3/8h/r06eOaYTp3Nqi+vt61zeFwqK2tTQ0NDResOXr0aKffP3bsWKdZrG+z2WwKDw93+wAAgN7Jo9BUWFion/3sZ5K+mW2ZO3eujh49qrvvvlsvv/yy15obN26cPvvsM1VWVro+I0eOVGZmpiorKxUfHy+Hw+EKcNI378XbvHmz6914ycnJCg4Odqupra3Vzp07XTWpqalyOp0qLy931Wzfvl1Op5N37AEAAElSgDHG+LqJ72Ls2LG66aab9Pvf/16S9NRTTyk/P19/+MMflJCQoLy8PH344YduSw489NBD+stf/qKVK1cqIiJCc+fO1VdffeW25MAdd9yhI0eOaPny5ZK+WXJg8ODB32nJgaamJtntdjmdTmadAADoIayevy2v0/RdngzrzsDw6KOP6uTJk8rOzlZDQ4NGjRqlDRs2uAKTJD3zzDPq06ePJk+erJMnT2rcuHFauXKlKzBJ0urVqzVz5kzXU3YZGRkqLCzstuMAAAD+zfJMU2BgoOWbq9vb273SXE/DTBMAAD2P12eaeN8cAAC4klkOTWPGjLmcfQAAAPg1j989J0ktLS1dvnvu3PfDAQAA9HQehaZjx47pgQce0Pr167vcfqXe0wQAAHovj9ZpysnJUUNDg7Zt26bQ0FAVFxfr1VdfVUJCgt555x1v9wgAAOBzHs00ffDBB/rzn/+sm2++WYGBgRo8eLAmTJig8PBw5efnu95LBwAA0Ft4NNN04sQJ1wtuIyIidOzYMUnS8OHD9cknn3ivOwAAAD/hUWgaMmSI9uzZI0m66aabtHz5ch0+fFjLli3ToEGDvNogAACAP/Do8lxOTo5qa2slSbm5ubr99tu1atUqhYSE6NVXX/VqgwAAAP7gkt89Z4zRyZMntXv3bl1zzTWKjIz0Vm89DiuCAwDQ81g9f3t0eU6SXn75ZSUmJqpv374aMGCA7rvvPr399tue7g4AAMCveXR57rHHHtMzzzyjGTNmKDU1VZJUVlamWbNm6X/+53/0xBNPeLVJAAAAX/Po8lxkZKSee+453XvvvW7jb7zxhmbMmKEvv/zSaw32JFyeAwCg57msl+fa29s1cuTITuPJyck6c+aMJ7sEAADwax6Fpp///Od64YUXOo2vWLFCmZmZl9wUAACAv7F8T9Ps2bNd/x0QEKCXXnpJGzZsUEpKiiRp27ZtOnjwoO677z7vdwkAAOBjlkPTp59+6vZ3cnKyJGnfvn2SpKuuukpXXXWVqqurvdgeAACAf7AcmjZt2nQ5+wAAAPBrHq/TBAAAcCUhNAEAAFhAaAIAALCA0AQAAGABoQkAAMACQhMAAIAFhCYAAAALCE0AAAAWEJoAAAAsIDQBAABYQGgCAACwgNAEAABgAaEJAADAAkITAACABYQmAAAACwhNAAAAFhCaAAAALCA0AQAAWEBoAgAAsIDQBAAAYAGhCQAAwAJCEwAAgAWEJgAAAAsITQAAABYQmgAAACwgNAEAAFhAaAIAALCA0AQAAGABoQkAAMACQhMAAIAFhCYAAAALCE0AAAAWEJoAAAAsIDQBAABY4PehKT8/XzfffLPCwsIUFRWlf/iHf9CePXvcaowxWrhwoWJiYhQaGqqxY8equrraraa1tVUzZsxQZGSk+vfvr4yMDB06dMitpqGhQVlZWbLb7bLb7crKylJjY+PlPkQAANAD+H1o2rx5sx5++GFt27ZNJSUlOnPmjCZOnKgTJ064apYsWaKCggIVFhbq448/lsPh0IQJE9Tc3OyqycnJ0dq1a1VUVKQtW7bo66+/Vnp6utrb2101U6ZMUWVlpYqLi1VcXKzKykplZWV16/ECAAA/ZXqY+vp6I8ls3rzZGGNMR0eHcTgcZvHixa6aU6dOGbvdbpYtW2aMMaaxsdEEBweboqIiV83hw4dNYGCgKS4uNsYYs2vXLiPJbNu2zVVTVlZmJJndu3db6s3pdBpJxul0XvJxAgCA7mH1/O33M03ncjqdkqSIiAhJUk1Njerq6jRx4kRXjc1m05gxY7R161ZJUkVFhU6fPu1WExMTo8TERFdNWVmZ7Ha7Ro0a5apJSUmR3W531ZyrtbVVTU1Nbh8AANA79ajQZIzR7NmzddtttykxMVGSVFdXJ0mKjo52q42OjnZtq6urU0hIiAYMGHDBmqioqE6/GRUV5ao5V35+vuv+J7vdrtjY2Es7QAAA4Ld6VGiaPn26qqqq9MYbb3TaFhAQ4Pa3MabT2LnOremq/kL7mT9/vpxOp+tz8OBBK4cBAAB6oB4TmmbMmKF33nlHmzZt0ve//33XuMPhkKROs0H19fWu2SeHw6G2tjY1NDRcsObo0aOdfvfYsWOdZrHOstlsCg8Pd/sAAIDeye9DkzFG06dP11tvvaUPPvhAcXFxbtvj4uLkcDhUUlLiGmtra9PmzZuVlpYmSUpOTlZwcLBbTW1trXbu3OmqSU1NldPpVHl5uatm+/btcjqdrhoAAHDl6uPrBi7m4Ycf1uuvv64///nPCgsLc80o2e12hYaGKiAgQDk5OcrLy1NCQoISEhKUl5enfv36acqUKa7aqVOnas6cORo4cKAiIiI0d+5cDR8+XOPHj5ckDR06VJMmTdK0adO0fPlySdKDDz6o9PR0DRkyxDcHDwAA/Ibfh6YXXnhBkjR27Fi38T/84Q/6xS9+IUl69NFHdfLkSWVnZ6uhoUGjRo3Shg0bFBYW5qp/5pln1KdPH02ePFknT57UuHHjtHLlSgUFBblqVq9erZkzZ7qessvIyFBhYeHlPUAAANAjBBhjjK+b6C2amppkt9vldDq5vwkAgB7C6vnb7+9pAgAA8AeEJgAAAAsITQAAABYQmgAAACwgNAEAAFhAaAIAALCA0AQAAGABoQkAAMACQhMAAIAFfv8aFQDwtfb2dlVVVen48eOKiIhQUlKS2yuYAFwZCE0AcAGlpaV6/vnnXS8LlySHw6Hs7GyNHj3ah50B6G5cngOA8ygtLVVubq7i4+O1dOlSrVu3TkuXLlV8fLxyc3NVWlrq6xYBdCNe2OtFvLAX6D3a29uVmZmp+Ph4PfHEEwoM/P9/Y3Z0dGjBggWqqanRqlWruFQH9HC8sBcALkFVVZXq6uqUmZnpFpgkKTAwUJmZmaqtrVVVVZWPOgTQ3QhNANCF48ePS5Li4uK63H52/GwdgN6P0AQAXYiIiJAk1dTUdLn97PjZOgC9H6EJALqQlJQkh8Oh1atXq6Ojw21bR0eHVq9erUGDBikpKclHHQLoboQmAOhCUFCQsrOzVVZWpgULFqi6ulotLS2qrq7WggULVFZWpoceeoibwIErCE/PeRFPzwG9T1frNA0aNEgPPfQQ6zQBvYTV8zehyYsITUDvxIrgQO9m9fzNiuAAcBFBQUEaMWKEr9sA4GPc0wQAAGABoQkAAMACQhMAAIAF3NMEABfBjeAAJEITAFxQV0sOOBwOZWdns+QAcIXh8hwAnEdpaalyc3MVHx+vpUuXat26dVq6dKni4+OVm5ur0tJSX7cIoBuxTpMXsU4T0Hu0t7crMzNT8fHxeuKJJxQY+P//xuzo6NCCBQtUU1OjVatWcakO6OGsnr+ZaQKALlRVVamurk6ZmZlugUmSAgMDlZmZqdraWlVVVfmoQwDdjdAEAF04fvy4JCkuLq7L7WfHz9YB6P0ITQDQhYiICElSTU1Nl9vPjp+tA9D7EZoAoAtJSUlyOBxavXq1Ojo63LZ1dHRo9erVGjRokJKSknzUIYDuxpIDANCFoKAgZWdnKzc3V7/97W91yy23yGazqbW1VeXl5dq2bZsWLVrETeDAFYTQBADnMXr0aN1zzz168803VVZW5hoPCgrSPffcwzpNwBWG0AQA51FaWqo1a9YoJSVFt9xyi/r27atTp06pvLxca9as0bBhwwhOwBWEdZq8iHWagN6DdZqAKwfrNAHAJWCdJgDn4vIcAHTh2+s0dfXCXtZpAq48hCYA6MLZ9ZfWrl2rd999t9MLe9PT093qAPR+hCYA6EJSUpK+973v6cUXX1Rqaqoee+wxxcXFue5jeumllzRgwADWaQKuIIQmALiI9vZ2rVmzRs3NzQoLC1N7e7skiedogCsLoQkAulBVVaXGxkYNHjxY5eXlnbYPHjxY+/fvV1VVlUaMGOGDDgF0N56eA4AunL3Be//+/V1uPzvOjeDAlYPQBABd+Lu/+zvXf3e15EBXdQB6N0ITAHRhy5Ytrv/u6oW9XdUB6N0ITQDQhT179ni1DkDPR2gCgC6cfULOW3UAej5CEwB04dxLcpdaB6DnIzQBQBeOHDni1ToAPR+hCQC60NbW5tU6AD0foQkAuhAQEODVOgA9H6EJALrAPU0AzkVoOsfzzz+vuLg49e3bV8nJyfrv//5vX7cEAAD8AKHpW9asWaOcnBz99re/1aeffqof/ehHuuOOO3TgwAFftwYAAHyM0PQtBQUFmjp1qn75y19q6NCh+v3vf6/Y2Fi98MILvm4NAAD4WB9fN+Av2traVFFRoXnz5rmNT5w4UVu3bu3yO62trWptbXX93dTUdFl77C579+5VTU2Nr9uApJaWFu3bt8/XbeAiCgoKfN3CFenaa69Vv379fN3GFS8uLk7XXXedr9voFoSm//Pll1+qvb1d0dHRbuPR0dGqq6vr8jv5+flatGhRd7TXrZ577jnt2LHD120APcY777zj6xYAn/nhD3+oZ5991tdtdAtC0znOfXzYGHPeR4rnz5+v2bNnu/5uampSbGzsZe2vO8yYMYOZJj/BTJPvfJcglJGRcRk7wfkw0+Qf4uLifN1CtyE0/Z/IyEgFBQV1mlWqr6/vNPt0ls1mk81m6472utV11113xUy1AufzXULTt//xBKD34kbw/xMSEqLk5GSVlJS4jZeUlCgtLc1HXQHwlQ8//NCrdQB6PkLTt8yePVsvvfSSXnnlFX3++eeaNWuWDhw4oF//+te+bg2AD1wsEBGYgCsLl+e+5Z577tFXX32lxx9/XLW1tUpMTNS6des0ePBgX7cGwEc+/PBDjR07tstxAFeWAGOM8XUTvUVTU5PsdrucTqfCw8N93Q4AALDA6vmby3MAAAAWEJoAAAAsIDQBAABYQGgCAACwgNAEAABgAaEJAADAAkITAACABYQmAAAACwhNAAAAFvAaFS86u7h6U1OTjzsBAABWnT1vX+wlKYQmL2pubpYkxcbG+rgTAADwXTU3N8tut593O++e86KOjg4dOXJEYWFhCggI8HU7ALyoqalJsbGxOnjwIO+WBHoZY4yam5sVExOjwMDz37lEaAIAC3ghNwBuBAcAALCA0AQAAGABoQkALLDZbMrNzZXNZvN1KwB8hHuaAAAALGCmCQAAwAJCEwAAgAWEJgAAAAsITQAAABYQmgAAACwgNAEAAFhAaAIAALCA0AQAAGDB/wLhuK5vNL2dpQAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import seaborn as sns\n",
    "sns.boxplot(modelling_df, y = 'balance_v_income' )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "823c1420-27a6-4893-9810-c4fb916e90a1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
